### ISSUE TITLE
Topic functionaliteit inbouwen.

### ISSUE THREAD

**Issue by thijsgelton** [MSDA-LifeCycleAgents/mlaf-arduino#11]

**Comment by thijsgelton** [comment]
@rogierpijpers dit heb jij zo gebouwd toch :P?

**Comment by rogierpijpers** [comment]
SensorAgent moet AID van proxy opslaan... deze wordt altijd de envelope->to.
Afhankelijk van topic of niet (en response van DA?) Topic of DecisionAgent AID opslaan als envelope->intendedReceiver
