### ISSUE TITLE
Doxygen (of iets anders) documentatie toevoegen aan framework klassen die als API gebruikt worden

### ISSUE THREAD

**Issue by rogierpijpers** [MSDA-LifeCycleAgents/mlaf-arduino#14]
Dus Agent, SensorAgent enzovoort.

Graag ook even noemen in de readme onder Usage (waar nu een to do staat)

**Comment by martijnvandijk** [comment]
Remco is al bezig met deze documentatie op feature/refactoring. Ik ga hem even vragen of hij al klaar is met zijn changes.

**Comment by Remco-Ruttenberg** [comment]
Added in 681f31b90cb0ff6c01b26790c7f584bc35f213ad
