### ISSUE TITLE
SensorReading content raakt malformed na de eerste send

### ISSUE THREAD

**Issue by rogierpijpers** [MSDA-LifeCycleAgents/mlaf-arduino#18]
Ik vraag me sowieso af, worden oude sensorreadings geleegd nadat ze verzonden zijn? volgens mij niet. Eerste sensor reading gaat goed, vervolgens komen er dingen zoals dit uit: ⸮⸮⸮⸮⸮⸮

**Comment by martijnvandijk** [comment]
komt die vreemde output in de xml terecht, zo ja in welke tags dan?

**Comment by rogierpijpers** [comment]
content dus. (lees: sensorreadings)

**Comment by rogierpijpers** [comment]
In sommige gevallen is de content ook leeg, dus: <content></content> als je je af vroeg welke tags. Dit gebeurd overigens ook willekeurig bij het versturen van de instructieset

**Comment by martijnvandijk** [comment]
heb je een voorbeeld van de output?

**Comment by rogierpijpers** [comment]
Bijvoorbeeld: 

<?xml version="1.0" encoding="UTF-8"?>
<envelope>
    <params index="1">
        <intended-receiver>
            <agent-identifier>
                <name>sometopic@TOPIC_</name>
                <addresses>
                    <url>tcp://TOPIC_:0</url>
                </addresses>
            </agent-identifier>
        </intended-receiver>
        <from>
            <agent-identifier>
                <name>NonCriticalSensorStuffAgent</name>
                <addresses>
                    <url>tcp://192.168.178.13:1234</url>
                </addresses>
            </agent-identifier>
        </from>
        <to>
            <agent-identifier>
                <name>tcpMtpAgent@192.168.178.14:1099/JADE</name>
                <addresses>
                    <url>tcp://192.168.178.14:6789</url>
                </addresses>
            </agent-identifier>
        </to>
        <acl-representation>fipa.acl.rep.string.std</acl-representation>
        <payload-encoding>US-ASCII</payload-encoding>
        <payload-length>679</payload-length>
    </params>
</envelope>

<fipa-message communicative-act="INFORM">
    <sender>
        <agent-identifier>
            <name>NonCriticalSensorStuffAgent</name>
            <addresses>
                <url>tcp://192.168.178.13:1234</url>
            </addresses>
        </agent-identifier>
    </sender>
    <receiver>
        <agent-identifier>
            <name>sometopic@TOPIC_</name>
            <addresses>
                <url>tcp://TOPIC_:0</url>
            </addresses>
        </agent-identifier>
    </receiver>
    <content>E</content>
    <language></language>
    <ontology>sensor-agent-reading</ontology>
    <protocol></protocol>
    <conversation-id></conversation-id>
</fipa-message>

**Comment by Remco-Ruttenberg** [comment]
Fixed in #22
