### ISSUE TITLE
Program crashes when receiving or sending a large message from/to JADE

### ISSUE THREAD

**Issue by riberts** [MSDA-LifeCycleAgents/mlaf-arduino#21]
The Program crashes when it receives a message from JADE. 
it goes wrong in the file (...) in the function (...)

the things that we've already tried are:

- All the different methodes to convert a string into a char array that we could find.
- Looked at the memory usage of the program and it seems okay (still not sure if it actually is)

**Comment by Remco-Ruttenberg** [comment]
The program crashes on in the MessageParser.h file in the toXML() function.
Partly related to the small amount of memory available.
The used library (tinyxml2) crashes on the Print function when printing to memory, not to stdout. When each character of the message content was replaced by an arbitrary chosen character, it did not crash.

Possible solutions:
- Use a different format for the message content
- Print to a file and read it back at a later moment
- Use a different XML library

**Comment by Remco-Ruttenberg** [comment]
Partial fix in #22 
Due to limited memory on the device messages should be as small as possible, otherwise they cause a crash.
