### ISSUE TITLE
Messaging systeem bestendig maken voor verkeerde input

### ISSUE THREAD

**Issue by rogierpijpers** [MSDA-LifeCycleAgents/mlaf-arduino#6]
Moet inkomende berichten met de volgende shit kunnen handelen:
- onbekende performative
- geen sender / receiver (en geen naam / address)
- geen "fipa-message" root element
- geen envelope
- content optioneel maken

Wanneer niet voldoet: NOT_UNDERSTOOD terug sturen.

**Comment by riberts** [comment]
dit is gedaan, moet alleen nog getest worden
